### ISSUE TITLE
[Craft 3] basicAuth implementation yields Undefined index error

### ISSUE THREAD

**Issue by andrewmenich** [sjelfull/craft3-autologin#11]
### Describe the bug

When using the basicAuth configuration, the basicAuth loop [here](https://github.com/verbb/autologin/blob/798cfd73fd1ff880c8ed85225b529a6fcce00c27/src/services/Service.php#L66) yields an `Undefined index` error due to the Auth Username being used as the key instead of the Craft username. 

The most straightforward solution is to simply pass the craft username variable to the login method, e.g.

```diff
- return $this->_loginByUsername($settings->basicAuth[$currentAuthUser]);
+ return $this->_loginByUsername($craftUsername);
```

Please let me know if I've misunderstood something here. If not, I'm happy to submit a PR

### Steps to reproduce

1. Add a `basicAuth` array to the `autologin.php settings, e.g. 
```php
'basicAuth' => [
        'craftUsername' => 'basicAuthUsername'
    ],
```
2.  Make a GET request to the site using a `authorization: Basic encryptedbasicAuthUsername` header

### Craft CMS version

3.7.41

### Plugin version

2.0.1

### Multi-site?

No

**Comment by engram-design** [comment]
Thanks for letting me know, should be fixed in [2.0.2](https://github.com/verbb/autologin/releases/tag/2.0.2)
