### ISSUE TITLE
If autologin enabled for standard user by ip - admin user can't login

### ISSUE THREAD

**Issue by mmc501** [sjelfull/craft3-autologin#5]
I have enabled Autologin by IP for standard users so they get logged into the front end.  

```
<?php
return [
    // Enable the Autologin plugin
    'enabled'           => true,

    // A list of Craft usernames/emails mapped to IPs
    'ipWhitelist'       => [
        'staff' => [
            '127.0.0.1',
            '162.247.141.59',
        ],
    ]

];
```

But if another user who is an admin on the same network tried to login - by the /admin url - it says the user account doesn't have access to the admin as they have been autologged in with the staff account above.

Is there a way around this? Or would I need to enable autologin by a url key instead?

**Comment by engram-design** [comment]
That's a tricky scenario because it'd be looking at the external IP of the network, not the internal IP. There's probably not a way around this, and would indeed recommend using URL keys instead, sorry!
