### ISSUE TITLE
Plugin does not redirect to control panel dashboard with cp=true

### ISSUE THREAD

**Issue by wimlatour** [sjelfull/craft3-autologin#6]
When setting the `cp=true` parameter in the autologin url, the user does not get redirected to the control panel dashboard, but to the root of the site (/) instead.

Changing the following code in `src/services/AutologinService.php`, line 132 seems to fix this issue:
```
- Craft::$app->response->redirect(UrlHelper::cpUrl('/'));
+ Craft::$app->response->redirect(UrlHelper::cpUrl());
```

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/autologin/releases/tag/2.0.1)
