### ISSUE TITLE
Craft 4 Compatibility?

### ISSUE THREAD

**Issue by mmc501** [sjelfull/craft3-autologin#7]
Hi, will this plugin be updated for Craft 4?

**Comment by gixxy22** [comment]
Also requesting this if possible.

**Comment by engram-design** [comment]
We've recently acquired this plugin from the Superbig team. Read our [blog post](https://verbb.io/blog/some-plugins-from-superbig) for more details.

**Comment by engram-design** [comment]
Added in [3.0.0](https://github.com/verbb/autologin/releases/tag/3.0.0)
