### ISSUE TITLE
cant login after removing superbig repo and installing verbb repo

### ISSUE THREAD

**Issue by gixxy22** [sjelfull/craft3-autologin#9]
### Describe the bug

Unknown Method – [yii\base\UnknownMethodException](http://www.yiiframework.com/doc-2.0/yii-base-unknownmethodexception.html)
Calling unknown method: craft\web\User::getUserByUsernameOrEmail()

### Steps to reproduce

Getting the following error after following the update instructions. had to disable to plugin in order to access cp.

Unknown Method – [yii\base\UnknownMethodException](http://www.yiiframework.com/doc-2.0/yii-base-unknownmethodexception.html)
Calling unknown method: craft\web\User::getUserByUsernameOrEmail()

### Craft CMS version

Craft Pro 3.7.48

### Plugin version

2.0.0

### Multi-site?

yes

**Comment by engram-design** [comment]
Fixed in [2.0.1](https://github.com/verbb/autologin/releases/tag/2.0.1)
